#!/usr/bin/env php
<?php

// clear test settings
if (file_exists(__DIR__ . "/tests/App/.test"))
    unlink(__DIR__ . "/tests/App/.test");

// start laravel

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/tests/App/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
